# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_test', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('id_cand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='president.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('id_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='president.Information')),
            ],
        ),
        migrations.CreateModel(
            name='Subunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='subunit',
            name='id_subunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subunit', to='president.Unit'),
        ),
        migrations.AddField(
            model_name='subunit',
            name='id_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='president.Unit'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='id_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='president.Unit'),
        ),
        migrations.AddField(
            model_name='result',
            name='id_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='president.Unit'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='president.Question'),
        ),
    ]
